---
# Tasks file for bindutils.yml
- hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
    - name: Install bind-utils
      yum: 
        name: bind-utils
        state: installed
